<?php
/**
 * Copyright © 2022 - Code Infinity. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Justin Bruce <justin@codeinfinity.co.za>
 */
/**
 * @var \C8EEE\Widgets\Block\Widget\Brochure $block
 */
?>
<div class="guzzle-holder" align="center">
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <link rel="stylesheet" href="//www.guzzle.co.za/crossdomain.css" type="text/css" />
    <script type="text/javascript" src="//www.guzzle.co.za/crossdomain.js"></script>
    <div class="guzzle" data-catalogue="Midas2"></div>
    <div class="guzzle-link">Powered by <a href="https://www.guzzle.co.za/midas/" target="_blank" title="Guzzle"> Guzzle </a></div>
    <br/>
</div>